Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "ibenmainS" do |control|
    control.vm.hostname = "ibenmainS"
    control.vm.network "private_network", ip: "192.168.56.110"
    
    control.vm.provider "virtualbox" do |vb|
      vb.name = "ibenmainS"
      vb.memory = 2048
      vb.cpus = 2
    end

    control.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y curl
      
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --node-ip 192.168.56.110" sh -
      
      echo "Waiting for K3s to be ready..."
      sleep 10

      if [ -d "/vagrant/confs" ]; then
        kubectl apply -f /vagrant/confs/
      else
        echo "Error: /vagrant/confs folder not found!"
      fi
    SHELL
  end
end