Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  # config.vm.boot_timeout = 600

  config.vm.define "ibenmainS" do |control|
    control.vm.hostname = "ibenmainS"
    control.vm.network "private_network", ip: "192.168.56.110"
    
    control.vm.provider "virtualbox" do |vb|
      vb.name = "ibenmainS"
      vb.memory = 2048
      vb.cpus = 2
    end

    control.vm.provision "shell", inline: <<-SHELL
      # ufw disable
      
      apt-get update -y
      apt-get install -y curl
      
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.110 --bind-address 0.0.0.0 --advertise-address 192.168.56.110 --write-kubeconfig-mode 644" sh -
      
      sleep 10
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  config.vm.define "ibenmainSW" do |worker|
    worker.vm.hostname = "ibenmainSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ibenmainSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    ``
    worker.vm.provision "shell", inline: <<-SHELL
      # ufw disable
      apt-get update -y
      apt-get install -y curl
      
      while [ ! -f /vagrant/node-token ]; do sleep 2; done

      TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN INSTALL_K3S_EXEC="--node-ip 192.168.56.111" sh -
    SHELL
  end
end